<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Toggle navigation_caret</name>
   <tag></tag>
   <elementGuidId>70227ca6-5e64-4934-98e0-78563edf827a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.caret</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbar']/div/ul/li[3]/a/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c3f4a204-4128-4e53-8088-ec636e011b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>caret</value>
      <webElementGuid>17c50a2c-583b-4319-8bd4-268ac3898319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar&quot;)/div[@class=&quot;navbar-right menu-bar&quot;]/ul[@class=&quot;nav navbar-nav weblinks&quot;]/li[@class=&quot;weblink  dropdown&quot;]/a[@class=&quot;dropdown-toggle&quot;]/span[@class=&quot;caret&quot;]</value>
      <webElementGuid>03dc3e1e-1b78-41e3-b4fc-c0d10c932de5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbar']/div/ul/li[3]/a/span</value>
      <webElementGuid>349402d5-437f-4b76-baa1-2affcae69dd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/a/span</value>
      <webElementGuid>328f005e-d1b6-484e-b09a-ba886a9f46d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@class = 'caret']</value>
      <webElementGuid>3c906343-8569-49bb-a7da-fb50a12cfe6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
