<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_DataDrivenFile</name>
   <tag></tag>
   <elementGuidId>0e489254-5ce7-41dc-be35-5a8d47387254</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.name.trimmedTextWithEllipsis.ng-star-inserted.cdk-focused.cdk-mouse-focused</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Include in app'])[1]/following::a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f0546126-ae03-45b3-93d1-3a0b2a9ccca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener noreferrer</value>
      <webElementGuid>630612f7-1e6f-42e1-9c25-880bb81980c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>queryparamshandling</name>
      <type>Main</type>
      <value>merge</value>
      <webElementGuid>70d449b2-7318-4ba8-8501-6d39222ddb01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>name trimmedTextWithEllipsis ng-star-inserted cdk-focused cdk-mouse-focused</value>
      <webElementGuid>f870128f-f5bf-452a-a46e-60996fc9bb0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/groups/02920506-5cc8-4c16-b824-fa2f5eb841cf/workbooks/1_51759_4522981?language=en-US</value>
      <webElementGuid>7523bf8c-73ef-4089-9bd1-9334e348a8e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>eb26218a-8e0b-423e-bdbd-fbe226cc8d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pbi-focus-tracker-idx</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>51a9c031-1c4b-4267-b7d9-c29311a3f27b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> DataDrivenFile </value>
      <webElementGuid>d724bc91-2522-4d7b-9e0f-874de4de199d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;artifactContentView&quot;)/div[@class=&quot;cdk-virtual-scroll-content-wrapper&quot;]/div[@class=&quot;row ng-star-inserted cdk-focused cdk-mouse-focused&quot;]/div[@class=&quot;fluent-cell ng-star-inserted&quot;]/span[@class=&quot;col col-name ng-star-inserted focused&quot;]/a[@class=&quot;name trimmedTextWithEllipsis ng-star-inserted cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>aebe04ac-ce60-4a21-9498-86ea0ef7c23e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Include in app'])[1]/following::a[1]</value>
      <webElementGuid>d527cd3f-e4b2-4dd7-a5e0-af67e3faef9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sensitivity'])[1]/following::a[1]</value>
      <webElementGuid>1df48763-ae9b-4ec5-b12c-70cbaa5796b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Workbook'])[1]/preceding::a[1]</value>
      <webElementGuid>aae17680-1db9-4113-9882-3e9144a843bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon Workspace23'])[4]/preceding::a[1]</value>
      <webElementGuid>a1c00d6d-ed5b-4910-966a-900f270fbd29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DataDrivenFile']/parent::*</value>
      <webElementGuid>322315d2-93e8-4044-b3fa-16403d6b58ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//cdk-virtual-scroll-viewport[@id='artifactContentView']/div/div/div[2]/span/a</value>
      <webElementGuid>95385777-294b-4d51-92be-dcb0fd404598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'DataDrivenFile')]</value>
      <webElementGuid>00650ec0-af09-458e-9e8a-e8590594cf4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/groups/02920506-5cc8-4c16-b824-fa2f5eb841cf/workbooks/1_51759_4522981?language=en-US')]</value>
      <webElementGuid>fdbda9ca-5378-48d4-9c45-5dd66b1ab66e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>726f504b-66d1-46b6-ad8a-a21eed5fb31f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
