<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_focalPointCycleData</name>
   <tag></tag>
   <elementGuidId>91a99ade-c620-4c16-a59f-dd789cf39162</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.name.trimmedTextWithEllipsis.ng-star-inserted.cdk-focused.cdk-mouse-focused</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Include in app'])[1]/following::a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dfe00d9f-b5c3-404a-bd6a-bb0e3da4ffbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>noopener noreferrer</value>
      <webElementGuid>6a75d99c-d6cf-465f-9cc7-af6f0c051194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>queryparamshandling</name>
      <type>Main</type>
      <value>merge</value>
      <webElementGuid>b8775233-8b20-4a6d-9dca-8d39ee33fa2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>name trimmedTextWithEllipsis ng-star-inserted cdk-focused cdk-mouse-focused</value>
      <webElementGuid>42d2fc54-0810-4638-8d57-ae10e2e15232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/groups/5bf61501-c8a1-42ca-a43b-a8614a4fafd7/workbooks/1_51718_4521734?language=en-US</value>
      <webElementGuid>e5f4006b-c3e4-4c33-acb7-a0a0a15861a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>d5abd396-c7f5-483c-8b63-0de00cb4add9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pbi-focus-tracker-idx</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9bcc7cf7-57aa-406c-ae42-38d8ff69d1c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> focalPointCycleData </value>
      <webElementGuid>58dab9a2-aa23-4cf2-98f4-6346d24a4a44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;artifactContentView&quot;)/div[@class=&quot;cdk-virtual-scroll-content-wrapper&quot;]/div[@class=&quot;row ng-star-inserted cdk-focused cdk-mouse-focused&quot;]/div[@class=&quot;fluent-cell ng-star-inserted&quot;]/span[@class=&quot;col col-name ng-star-inserted focused&quot;]/a[@class=&quot;name trimmedTextWithEllipsis ng-star-inserted cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>9b8cd3db-8427-4bba-818e-013f19786c34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Include in app'])[1]/following::a[1]</value>
      <webElementGuid>0e18f4e6-c9b7-4e69-8a73-6f0af63b704f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sensitivity'])[1]/following::a[1]</value>
      <webElementGuid>b859fc5b-6896-4dd4-b581-0bb04537492a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Workbook'])[1]/preceding::a[1]</value>
      <webElementGuid>534f2d02-6c77-4ae2-948a-a1dab0588805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon Workspace2'])[4]/preceding::a[1]</value>
      <webElementGuid>519c5926-2b72-447b-be26-75732ab11376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='focalPointCycleData']/parent::*</value>
      <webElementGuid>6ce85a45-7017-4564-8609-81724ad3f4c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//cdk-virtual-scroll-viewport[@id='artifactContentView']/div/div/div[2]/span/a</value>
      <webElementGuid>d8f58782-8ab8-4d3a-9a05-9f1ae8f3fab0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'focalPointCycleData')]</value>
      <webElementGuid>ca8199f2-6898-4988-bfbc-203a2106da1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/groups/5bf61501-c8a1-42ca-a43b-a8614a4fafd7/workbooks/1_51718_4521734?language=en-US')]</value>
      <webElementGuid>d8bbac13-0411-47d7-846a-20586552ba37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>6fc2b98f-f525-4246-9e60-1ded9a8db8c8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
