<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Workspaces</name>
   <tag></tag>
   <elementGuidId>9d79bd19-c5db-4dfa-ba76-65325ca00c0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.workspacesPaneExpander.switcher.cdk-focused.cdk-mouse-focused</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn'])[1]/following::button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6ece703d-b3d6-4106-9b3a-63c60d7c26c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pbitooltipposition</name>
      <type>Main</type>
      <value>after</value>
      <webElementGuid>3950f7bb-c335-4e51-b23a-c22cf724657d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f45ad569-dc49-4e4f-8007-214edda93e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>workspacesPaneExpander switcher cdk-focused cdk-mouse-focused</value>
      <webElementGuid>b4819224-8370-4fba-aeca-47f388eedf3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Workspaces</value>
      <webElementGuid>e220ff8a-3a1c-4199-a630-89a47fa1a98a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pbi-focus-tracker-idx</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>fe1d9963-5c91-4680-b168-7aa45477cd73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Workspaces</value>
      <webElementGuid>1f5dd1e6-5142-4ecf-805e-5de8913d5ff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leftNavPane&quot;)/section[@class=&quot;navigationPane navigationPaneBody&quot;]/nav[1]/button[@class=&quot;workspacesPaneExpander switcher cdk-focused cdk-mouse-focused&quot;]</value>
      <webElementGuid>1a52a6ca-8019-4d33-b767-01b06efeae8b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn'])[1]/following::button[1]</value>
      <webElementGuid>c4dc0a09-c219-423c-bf35-97e081c2988e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deployment pipelines'])[1]/following::button[2]</value>
      <webElementGuid>cc5bebab-9f7e-4b14-b723-09db2d589663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Katalon Workspace2'])[2]/preceding::button[1]</value>
      <webElementGuid>931ff6d6-558f-49e5-9f97-cafe070c125b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get data'])[1]/preceding::button[2]</value>
      <webElementGuid>ea8ea2b1-d37e-44d9-9011-7ccfec64f380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//navigation-pane[@id='leftNavPane']/section/nav/button</value>
      <webElementGuid>6a713ecc-b7e8-409e-855b-da5008d100b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/button</value>
      <webElementGuid>1b37c074-f99e-44da-988b-02c8de5881f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
