<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Get</name>
   <tag></tag>
   <elementGuidId>3524d383-2b3b-4dff-b07e-4908890b2898</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Bring in your reports, workbooks, or data from Excel, Power BI Desktop or CSV files.'])[1]/following::button[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f76f1059-b9c8-4dc8-97f2-a130b677898b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>getBtn biButton primary trimmedTextWithEllipsis</value>
      <webElementGuid>a781829d-0cb1-4d84-b131-84d837e9f7bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>localize</name>
      <type>Main</type>
      <value>GetData_Get</value>
      <webElementGuid>83426ad2-7f29-4bc2-b43f-44c68558d4ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>localize-tooltip</name>
      <type>Main</type>
      <value>GetData_GetFiles</value>
      <webElementGuid>890cde6c-0f06-4a0f-9e60-07e78e7e572f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-disabled</name>
      <type>Main</type>
      <value>!isEnabled(3)</value>
      <webElementGuid>b03114ed-1220-4772-aeb9-16bc6a52c19b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Files, Get</value>
      <webElementGuid>58516909-2905-4372-9768-58f65f3eb09c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Files, Get</value>
      <webElementGuid>e2b281dd-cf51-43bc-8a50-3d9e87f09dcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pbi-focus-tracker-idx</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>5f79131e-a2ca-4f87-9a76-8bdd8ffb8f4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Get</value>
      <webElementGuid>d3663fa0-fb51-4cd4-93a5-c496e9dd361f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/modern-get-data[@class=&quot;ng-star-inserted&quot;]/lazy-load-legacy-content-slider[1]/content-provider-store-modern-wrapper[@class=&quot;sliderPane ng-star-inserted&quot;]/content-provider-store-modern[@class=&quot;sliderPane&quot;]/div[@class=&quot;sliderContentView contentProviderStore splashState&quot;]/div[@class=&quot;contentProviderSplash&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;contentContainer&quot;]/div[@class=&quot;dataSourceTiles&quot;]/section[@class=&quot;dataSourceTileGroup&quot;]/div[@class=&quot;dataSourceTile&quot;]/button[@class=&quot;getBtn biButton primary trimmedTextWithEllipsis&quot;]</value>
      <webElementGuid>34c577b7-0df8-43e4-b0de-3d7bf39e694c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bring in your reports, workbooks, or data from Excel, Power BI Desktop or CSV files.'])[1]/following::button[1]</value>
      <webElementGuid>612ed02d-94c9-40b8-9c70-d47d701220be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Files'])[2]/following::button[1]</value>
      <webElementGuid>6aae2984-e870-491f-9a7b-b3b03b719540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Databases'])[1]/preceding::button[1]</value>
      <webElementGuid>49f4f817-46d6-489b-a481-2d87d7f1fff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use Power BI Desktop to connect to data in Azure SQL Database and more.'])[1]/preceding::button[1]</value>
      <webElementGuid>2557edb9-396f-4f98-963c-57b38a3c1ce4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/modern-get-data/lazy-load-legacy-content-slider/content-provider-store-modern-wrapper/content-provider-store-modern/div/div[3]/div/div[2]/div/section[2]/div/button</value>
      <webElementGuid>301b6fe1-60a5-4fad-970b-d7acb310ca77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section[2]/div/button</value>
      <webElementGuid>e49a429c-24af-4266-9ae6-b5e4e7eb9327</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
