<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Remove</name>
   <tag></tag>
   <elementGuidId>c97152a4-4367-4057-9c36-0ec9dbdb5e04</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#okButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='okButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>dd112e93-d6eb-4c77-85d4-78a73a228b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>okButton</value>
      <webElementGuid>0ea6c5ec-b563-400a-861a-fc6aa1ebe6ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pbi-fluent-button primary primaryBtn</value>
      <webElementGuid>0dc799c2-dcf1-4a38-bb90-98705f7a63d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>69748d81-8fc6-43f7-a0e4-9d9dcae6b4c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pbi-focus-tracker-idx</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>4277bf52-113a-4d28-ad89-904bd2427faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Remove</value>
      <webElementGuid>b56a688c-874c-4244-a62e-9b44f2dfca1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;okButton&quot;)</value>
      <webElementGuid>2bac6219-1863-4b03-b741-d8cf0c3d8e53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='okButton']</value>
      <webElementGuid>597fb1af-c849-40fd-a945-5d157cb476dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to remove this workbook from Power BI?'])[1]/following::button[1]</value>
      <webElementGuid>37ed87d4-4ba9-4cde-97e2-b74c0c0945d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remove workbook'])[1]/following::button[2]</value>
      <webElementGuid>fe6a8ece-8cd4-4ee2-95d3-ca28ff67e593</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::button[1]</value>
      <webElementGuid>ca5095dc-bbbc-4655-87b8-bee80e61239a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'okButton', '&quot;', ')')])[1]/preceding::button[2]</value>
      <webElementGuid>794ba5a8-ec68-4e00-b0bc-11155e8aef34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Remove']/parent::*</value>
      <webElementGuid>777ef449-fb3a-4d1a-b2c5-da2f2970f832</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-dialog-container[@id='mat-dialog-0']/simple-confirmation-dialog/dialog-footer/mat-dialog-actions/div[2]/button</value>
      <webElementGuid>86baad3b-9604-4a73-9fc3-645a6dc4a488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//mat-dialog-actions/div[2]/button</value>
      <webElementGuid>d52a9146-79e9-4312-be28-cf0cd9028a84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
