<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>cdk-virtual-scroll-viewport_focalPointCycle_86c4f5</name>
   <tag></tag>
   <elementGuidId>53904a5d-2a04-4304-91c7-d829cff75827</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#artifactContentView</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//cdk-virtual-scroll-viewport[@id='artifactContentView']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>cdk-virtual-scroll-viewport</value>
      <webElementGuid>5a7b16ad-ceff-4694-93cd-87db2cc1375f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>itemsize</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>6c10aea4-6f02-4fe5-b8cf-108622e72623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>artifactContentView</value>
      <webElementGuid>67eb048b-e9cc-4db4-936f-2ab425fc1793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minbufferpx</name>
      <type>Main</type>
      <value>400</value>
      <webElementGuid>e7aadd2e-815f-4934-afe0-00c213308f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxbufferpx</name>
      <type>Main</type>
      <value>400</value>
      <webElementGuid>a564adc2-b929-4e55-943a-2b8a0891297f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cdk-virtual-scroll-viewport cdk-virtual-scroll-orientation-vertical ng-star-inserted</value>
      <webElementGuid>93a57460-e288-4095-9a58-ce3c3095b31f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> focalPointCycleData WorkbookKatalon Workspace2 14/04/22, 16:58:46  — —  Yes
</value>
      <webElementGuid>632799f0-f80a-4954-9405-7b655883aede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;artifactContentView&quot;)</value>
      <webElementGuid>639f2bb5-d9c4-460c-83da-3a423239925c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//cdk-virtual-scroll-viewport[@id='artifactContentView']</value>
      <webElementGuid>70d865ca-6b73-49f8-b7ac-e7e8eced54b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Include in app'])[1]/following::cdk-virtual-scroll-viewport[1]</value>
      <webElementGuid>c45c886b-7928-499a-b916-a2e96b8758d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sensitivity'])[1]/following::cdk-virtual-scroll-viewport[1]</value>
      <webElementGuid>f126b122-8b57-4d32-a003-15ff00c71fb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/workspace-view/fluent-workspace/mat-sidenav-container/mat-sidenav-content/fluent-workspace-list/fluent-list-table-base/div/cdk-virtual-scroll-viewport</value>
      <webElementGuid>77e2bee7-4e6b-4876-9b2a-26fb12672389</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//cdk-virtual-scroll-viewport</value>
      <webElementGuid>bd20904a-62ac-4d1e-a926-d2d39f480d13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
