<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_My workspace_glyphicon glyph-small pbi-gl_6cd8e7</name>
   <tag></tag>
   <elementGuidId>32aabfa5-3d46-4804-b5e8-3f19f08ea788</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.glyphicon.glyph-small.pbi-glyph-user.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='powerBIUserInfoBtn']/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>7cefcabd-bd3b-466a-b64d-bd04ce0579d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicon glyph-small pbi-glyph-user ng-star-inserted</value>
      <webElementGuid>9ef8fff5-4b04-42cb-a305-6fe31555331e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;powerBIUserInfoBtn&quot;)/i[@class=&quot;glyphicon glyph-small pbi-glyph-user ng-star-inserted&quot;]</value>
      <webElementGuid>414b5a02-df19-41ff-8120-b4961261ffcc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='powerBIUserInfoBtn']/i</value>
      <webElementGuid>157f4fe5-ca65-4c8d-8903-533a37bf1ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[8]/i</value>
      <webElementGuid>4db7cb79-d64b-418f-94dd-99cf9443d993</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
