<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Pin_workbookEWAIsolation</name>
   <tag></tag>
   <elementGuidId>e197e46f-76ea-4c41-abd5-0ccf71728036</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[name=&quot;workbookEWAIsolation&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@name = 'workbookEWAIsolation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e805b463-e0e1-4b81-b2b6-d963c96b0012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>workbookEWAIsolation</value>
      <webElementGuid>1785f1fd-915b-433f-aae8-6b58978225e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Excel Workbook</value>
      <webElementGuid>ef579939-fb45-429b-b94e-20c831d49402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/ewaIsolation.cshtml</value>
      <webElementGuid>cb6ab616-5e27-4e2d-a9da-5682bccad6bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>workbookEWAIsolation</value>
      <webElementGuid>c6498529-b667-41f8-842f-3ffa896a2990</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;workbookContainerWrapper&quot;)/iframe[@class=&quot;workbookEWAIsolation&quot;]</value>
      <webElementGuid>893464c2-8452-47a9-80f1-57163edf7673</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'workbookEWAIsolation']</value>
      <webElementGuid>8564f803-e82a-41fa-8150-d38e20a4a408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@name='workbookEWAIsolation']</value>
      <webElementGuid>13369b01-442e-4458-b122-b2a5919402cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='workbookContainerWrapper']/iframe</value>
      <webElementGuid>e65cabe3-fba0-4f8b-92de-866999290d21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>bf563961-0b9f-4cc2-aa40-fbc361c61183</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
