<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Workspace name_groupName</name>
   <tag></tag>
   <elementGuidId>8c4ab4c2-74e0-4f4c-bcc1-1d95820e866c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#folderName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = 'groupName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1a72e2e8-3bb8-41fb-93ed-b84c5e8680f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>folderName</value>
      <webElementGuid>f78fec2c-711b-4ba2-958d-4b710a4e4960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>localize-attr</name>
      <type>Main</type>
      <value>{placeholder: 'NameThisWorkspace', label: 'WorkspaceName'}</value>
      <webElementGuid>a382a360-6b8d-4b4b-8049-c313434c1c11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>groupName</value>
      <webElementGuid>f0feeed3-71da-4eae-9ba2-cfaacefa7bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3d580520-ddb3-47c8-8d85-ddb51a79b4cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>{errorFolderNameInput: !$ctrl.latestFolderNameIsValid} ng-pristine ng-untouched ng-empty ng-invalid ng-invalid-required ng-valid-maxlength</value>
      <webElementGuid>5a573b68-dc6e-4dbe-9a22-ac28cc942b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1b2b3660-a1bc-446b-937d-836aed03657e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f7210ba3-5fe4-4c5b-9904-28c40dadc79a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>256</value>
      <webElementGuid>7e1f549f-ecf8-48de-9353-82a65828e33f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$ctrl.model.groupName</value>
      <webElementGuid>200102a9-9269-4560-b9fa-73c31f02b0e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-change</name>
      <type>Main</type>
      <value>$ctrl.folderNameChanged()</value>
      <webElementGuid>2c449b82-01ac-49e5-9911-009a904a1c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>localize-tooltip</name>
      <type>Main</type>
      <value>GroupEditor_GroupName_Tooltip</value>
      <webElementGuid>a2be5848-f37b-4010-a8be-8eca1cc4ffc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Please fill out this field.</value>
      <webElementGuid>386c6c26-db23-421b-800b-0acf25791c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name this workspace</value>
      <webElementGuid>312d5682-6e91-4aac-928f-6f604406265c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>label</name>
      <type>Main</type>
      <value>Workspace name</value>
      <webElementGuid>b0aa148b-67ed-4678-ba70-37e84780443a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pbi-focus-tracker-idx</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>4745e825-ffde-45c4-8034-58ef4b1ce909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;folderName&quot;)</value>
      <webElementGuid>19da25d4-6c77-43ad-8118-93ff62a4535b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'groupName']</value>
      <webElementGuid>516ac651-9aae-4a90-9873-c2d601f9e5ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='folderName']</value>
      <webElementGuid>961003fa-5f15-4093-bc4f-68e756ba69cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-sidenav-content[@id='rootContent']/task-pane-slider-wrapper/task-pane-slider/div[3]/div/div/div/create-group-blade/ng-form/div/section/section/input</value>
      <webElementGuid>2a45d30f-b610-4a63-8e0e-d0b344d72036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/input</value>
      <webElementGuid>4f6f4f7e-1db2-4d22-991f-a2cf7cc13f9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
