<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_concat(You, , re about to delete this_ae28ac</name>
   <tag></tag>
   <elementGuidId>a2f40b06-52d7-46ea-95cb-665f536cab51</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input.undefined.primary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@value='Delete']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ee3cb5c-8637-4ca9-ae28-312b0a773a32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e01e561c-3c26-4a6c-973f-d39379e55a16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Delete</value>
      <webElementGuid>e017c47b-6c96-4c6e-be5e-f9890e267836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>undefined primary</value>
      <webElementGuid>edc8ee4b-8e15-4cd6-9ef1-84bce683d341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pbi-focus-tracker-idx</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>438df619-289d-409c-a0e0-724982d34da3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;cdk-focused cdk-program-focused&quot;]/body[1]/div[@class=&quot;infonav-modalContainerHost&quot;]/div[@class=&quot;infonav-modalContainer&quot;]/div[@class=&quot;infonav-modalDialog&quot;]/div[@class=&quot;infonav-dialogLayout themeableElement&quot;]/div[@class=&quot;infonav-dialogActions&quot;]/input[@class=&quot;undefined primary&quot;]</value>
      <webElementGuid>fca33ea8-25fc-4bbd-9610-cd7b190ba97d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@value='Delete']</value>
      <webElementGuid>64bdd95e-cf7a-4962-b6bf-c43a614cea3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>0e012237-1129-4fad-a360-60d5cb564b50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
