<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_Learn_mat-icon notranslate pbi-gly_6bd380</name>
   <tag></tag>
   <elementGuidId>36452755-788d-462a-9419-b59587f5f520</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>mat-icon.mat-icon.notranslate.pbi-glyph-font-face.pbi-glyph-group.mat-icon-no-color</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//navigation-pane[@id='leftNavPane']/section/nav/div/button/div[2]/workspace-icon/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>e9085722-684c-473c-aaf4-7389811e94ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7140843a-213d-4fe3-bc66-90c9c38e1b6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate pbi-glyph-font-face pbi-glyph-group mat-icon-no-color</value>
      <webElementGuid>5785fbc9-095f-46d2-917a-eb47213ee39f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8eef1f74-1a95-4c5f-baf1-32541b1b2a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>5fe14944-a1cd-48b7-9eee-0ac6f35ef02e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-name</name>
      <type>Main</type>
      <value>pbi-glyph-group</value>
      <webElementGuid>cd852ea3-2280-485e-83ad-7b4271e02144</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leftNavPane&quot;)/section[@class=&quot;navigationPane navigationPaneBody&quot;]/nav[1]/div[@class=&quot;paneExpanderHeader&quot;]/button[@class=&quot;workspaceName ng-star-inserted cdk-focused cdk-mouse-focused&quot;]/div[@class=&quot;workspaceIcon&quot;]/workspace-icon[@class=&quot;ng-star-inserted&quot;]/mat-icon[@class=&quot;mat-icon notranslate pbi-glyph-font-face pbi-glyph-group mat-icon-no-color&quot;]</value>
      <webElementGuid>8757d5df-a449-4501-b7bf-7f9356c85678</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//navigation-pane[@id='leftNavPane']/section/nav/div/button/div[2]/workspace-icon/mat-icon</value>
      <webElementGuid>5f0444cc-a34a-4ef1-a06e-276a383ed298</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//workspace-icon/mat-icon</value>
      <webElementGuid>402023ff-48fc-46d4-b0d0-2c34f8331207</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
