<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_Katalon Workspace2_mat-icon notran_7ac64e</name>
   <tag></tag>
   <elementGuidId>408cb0bb-4741-450a-9f9d-687774b3bd81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>workspace-button.groupContextMenuButton.selected > button.mat-menu-trigger.openMenu > mat-icon.mat-icon.notranslate.glyph-small.pbi-glyph-font-face.pbi-glyph-more.mat-icon-no-color</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cdk-overlay-5']/nav/nav-pane-workspaces/div[3]/virtual-scroll/div[2]/ul/li[3]/workspace-button/button[2]/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>afbf5764-5dcb-4baa-8a31-098c40e6c3f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>79e887aa-15fb-4342-9619-aeeec23e55e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fonticon</name>
      <type>Main</type>
      <value>pbi-glyph-more</value>
      <webElementGuid>15ef9a78-618a-40f7-9243-e160470236fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate glyph-small pbi-glyph-font-face pbi-glyph-more mat-icon-no-color</value>
      <webElementGuid>fc699c9c-1862-4a37-b537-427d9146fdd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c15ce481-498e-4447-a131-53bc4b66a0fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>71ce1951-8371-4ae4-bf95-0560dfddb2c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-name</name>
      <type>Main</type>
      <value>pbi-glyph-more</value>
      <webElementGuid>0c0d8e94-5f6f-430f-ad33-80886cbacb3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cdk-overlay-5&quot;)/nav[@class=&quot;ng-star-inserted&quot;]/nav-pane-workspaces[@class=&quot;fluent-theme&quot;]/div[@class=&quot;workspaces&quot;]/virtual-scroll[@class=&quot;nav-pane-quick-virtual-scroll vertical selfScroll&quot;]/div[@class=&quot;scrollable-content&quot;]/ul[1]/li[@class=&quot;ng-star-inserted&quot;]/workspace-button[@class=&quot;groupContextMenuButton selected&quot;]/button[@class=&quot;mat-menu-trigger openMenu&quot;]/mat-icon[@class=&quot;mat-icon notranslate glyph-small pbi-glyph-font-face pbi-glyph-more mat-icon-no-color&quot;]</value>
      <webElementGuid>614b5509-a810-40eb-b465-b058a0c6bca4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cdk-overlay-5']/nav/nav-pane-workspaces/div[3]/virtual-scroll/div[2]/ul/li[3]/workspace-button/button[2]/mat-icon</value>
      <webElementGuid>84782e98-963f-4bec-9dca-bb0a554e04a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[3]/workspace-button/button[2]/mat-icon</value>
      <webElementGuid>4f873e91-7cd7-4246-9a3d-1a55a1fd668b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
