<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_DataDrivenFile_mat-icon notranslat_a216a3</name>
   <tag></tag>
   <elementGuidId>4c351473-11f7-488a-9456-a7ef30b2ae23</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>mat-icon.mat-icon.notranslate.glyph-small.pbi-glyph-font-face.pbi-glyph-more.mat-icon-no-color.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//cdk-virtual-scroll-viewport[@id='artifactContentView']/div/div/div[2]/span/workbook-context-menu/button/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>334715cb-ff71-4588-b847-39ed5b60f3cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>611d64bf-216f-4016-9764-224554ef95d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate glyph-small pbi-glyph-font-face pbi-glyph-more mat-icon-no-color ng-star-inserted</value>
      <webElementGuid>ea03cfd1-839c-42ad-aae4-72f25abef62f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>76b09f02-9f1d-4201-82cb-3ad0a2577098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>010ddd7b-cef5-4d49-b651-36aa69d4f304</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-name</name>
      <type>Main</type>
      <value>pbi-glyph-more</value>
      <webElementGuid>3b8a673f-df01-4045-9857-fde7d0cbafd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;artifactContentView&quot;)/div[@class=&quot;cdk-virtual-scroll-content-wrapper&quot;]/div[@class=&quot;row ng-star-inserted cdk-focused cdk-mouse-focused&quot;]/div[@class=&quot;fluent-cell ng-star-inserted&quot;]/span[@class=&quot;col col-name ng-star-inserted focused&quot;]/workbook-context-menu[@class=&quot;context-menu ng-star-inserted&quot;]/button[@class=&quot;mat-menu-trigger menuTrigger cdk-focused cdk-mouse-focused&quot;]/mat-icon[@class=&quot;mat-icon notranslate glyph-small pbi-glyph-font-face pbi-glyph-more mat-icon-no-color ng-star-inserted&quot;]</value>
      <webElementGuid>499d2b63-d6e0-48d6-800a-cba0faafd779</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//cdk-virtual-scroll-viewport[@id='artifactContentView']/div/div/div[2]/span/workbook-context-menu/button/mat-icon</value>
      <webElementGuid>62b2a34c-5705-448d-88c8-a96bfad6edca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//workbook-context-menu/button/mat-icon</value>
      <webElementGuid>1bdcd968-939d-4da6-b2ca-d051b92e8636</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
