<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_focalPointCycleData_mat-icon notra_507719</name>
   <tag></tag>
   <elementGuidId>8c81ec9d-1e44-4b3c-a97b-d9c2c9854d3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>mat-icon.mat-icon.notranslate.glyph-small.pbi-glyph-font-face.pbi-glyph-more.mat-icon-no-color.ng-star-inserted</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//cdk-virtual-scroll-viewport[@id='artifactContentView']/div/div/div[2]/span/workbook-context-menu/button/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>c6f3942d-889c-428a-aee3-61c95f8f1809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>5d1a7f5a-e078-486d-9ee4-dc6abb610c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate glyph-small pbi-glyph-font-face pbi-glyph-more mat-icon-no-color ng-star-inserted</value>
      <webElementGuid>54cd66f1-3a0e-4aaf-b45d-c52dc994a0cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f8088f93-f17b-4a54-9c10-b1ef478e0802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>18ae93ac-e458-44d9-8da6-b720b6073afa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-name</name>
      <type>Main</type>
      <value>pbi-glyph-more</value>
      <webElementGuid>0f8dc4fe-b6db-423b-a037-003c9b7c0bea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;artifactContentView&quot;)/div[@class=&quot;cdk-virtual-scroll-content-wrapper&quot;]/div[@class=&quot;row ng-star-inserted cdk-focused cdk-mouse-focused&quot;]/div[@class=&quot;fluent-cell ng-star-inserted&quot;]/span[@class=&quot;col col-name ng-star-inserted focused&quot;]/workbook-context-menu[@class=&quot;context-menu ng-star-inserted&quot;]/button[@class=&quot;mat-menu-trigger menuTrigger cdk-focused cdk-mouse-focused&quot;]/mat-icon[@class=&quot;mat-icon notranslate glyph-small pbi-glyph-font-face pbi-glyph-more mat-icon-no-color ng-star-inserted&quot;]</value>
      <webElementGuid>62f75b53-1b7b-4070-9fff-8481402e2097</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//cdk-virtual-scroll-viewport[@id='artifactContentView']/div/div/div[2]/span/workbook-context-menu/button/mat-icon</value>
      <webElementGuid>72b8fac8-bfbe-40ec-b223-d029094d20bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//workbook-context-menu/button/mat-icon</value>
      <webElementGuid>a1cf0d9a-efb3-4132-a0a2-6af46dc446bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
