<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>mat-icon_Learn_mat-icon notranslate typeIco_c5185a</name>
   <tag></tag>
   <elementGuidId>660bee22-bfbf-4c77-b047-9470e6332f6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>mat-icon.mat-icon.notranslate.typeIcon.pbi-glyph-font-face.pbi-glyph-collections.mat-icon-no-color</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//navigation-pane[@id='leftNavPane']/section/nav/button/mat-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>mat-icon</value>
      <webElementGuid>8314e93f-445c-4cdb-a77f-1d25d76bfe87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8d925188-8f1d-4b80-9e73-82d1df25c23d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fonticon</name>
      <type>Main</type>
      <value>pbi-glyph-collections</value>
      <webElementGuid>2c45c4c0-ae6b-4ff7-831e-c3fabb8c0fcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mat-icon notranslate typeIcon pbi-glyph-font-face pbi-glyph-collections mat-icon-no-color</value>
      <webElementGuid>d463efa8-6d93-4b65-8418-c38fa474b198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b6b50f92-e9b5-4688-a9e3-3a98ddf41a49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-type</name>
      <type>Main</type>
      <value>font</value>
      <webElementGuid>da34afa6-05a3-47eb-81fb-472ec1dde472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mat-icon-name</name>
      <type>Main</type>
      <value>pbi-glyph-collections</value>
      <webElementGuid>adb4ae72-95f8-4db1-aee2-b2715ebfa886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;leftNavPane&quot;)/section[@class=&quot;navigationPane navigationPaneBody&quot;]/nav[1]/button[@class=&quot;workspacesPaneExpander switcher cdk-focused cdk-mouse-focused&quot;]/mat-icon[@class=&quot;mat-icon notranslate typeIcon pbi-glyph-font-face pbi-glyph-collections mat-icon-no-color&quot;]</value>
      <webElementGuid>c4ee9b28-dd35-4494-97f2-ed4c410a0390</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//navigation-pane[@id='leftNavPane']/section/nav/button/mat-icon</value>
      <webElementGuid>117b0653-800f-4e8c-9cbe-8e0c64393117</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/button/mat-icon</value>
      <webElementGuid>d4b32e17-8cd4-4a3b-9678-302bbeb45b07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
