<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Description_description</name>
   <tag></tag>
   <elementGuidId>f27dded7-9fe2-4c9a-abfc-b64ad14e3e80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea[name=&quot;description&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@name = 'description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>c18d0dd4-7c74-490a-b62c-18363307d087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>localize-attr</name>
      <type>Main</type>
      <value>{placeholder: 'DescribeThisWorkspace'}</value>
      <webElementGuid>a4dfcfe6-18cd-440d-b10f-25b042c48fe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>7c0e24d5-4498-4166-8d49-abee938d734d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>folderDescriptionBox ng-untouched ng-valid ng-valid-maxlength ng-not-empty ng-dirty ng-valid-parse</value>
      <webElementGuid>001e9395-8cf9-40bf-aca4-d01e6061c2d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4000</value>
      <webElementGuid>58712836-d721-4b77-9a46-c076c5c1a98f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-model</name>
      <type>Main</type>
      <value>$ctrl.model.description</value>
      <webElementGuid>4dc1df97-82a9-4e1d-8e50-9c06cf3803c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>localize-tooltip</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>6b827c31-2d0d-409d-92cc-791bfdcfe0af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>2e9bf11c-b47d-41df-a416-47c756c5a3f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Describe this workspace</value>
      <webElementGuid>af23050d-ad8c-488c-a0c3-71f63f2f8508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pbi-focus-tracker-idx</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>a12d740d-49c1-4091-8e89-975b3b8ebe88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rootContent&quot;)/task-pane-slider-wrapper[@class=&quot;ng-star-inserted&quot;]/task-pane-slider[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;taskPaneSliderView&quot;]/div[@class=&quot;collapsiblePane greyBackground expanded largeWidth&quot;]/div[@class=&quot;innerLayout&quot;]/div[@class=&quot;contentFrameHost&quot;]/create-group-blade[1]/ng-form[@class=&quot;ng-valid-maxlength ng-dirty ng-valid-parse ng-valid ng-valid-required&quot;]/div[@class=&quot;groupsEditorBlade paneLayout&quot;]/section[@class=&quot;contentContainer&quot;]/section[@class=&quot;bladeInnerContent&quot;]/textarea[@class=&quot;folderDescriptionBox ng-untouched ng-valid ng-valid-maxlength ng-not-empty ng-dirty ng-valid-parse&quot;]</value>
      <webElementGuid>6bffec5c-b588-49d7-b94c-eeda913e7e38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'description']</value>
      <webElementGuid>9ff40c76-752a-467d-abef-f38ae0b06207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@name='description']</value>
      <webElementGuid>0c9ddd31-c770-4847-bca6-d55ee6e38920</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//mat-sidenav-content[@id='rootContent']/task-pane-slider-wrapper/task-pane-slider/div[3]/div/div/div/create-group-blade/ng-form/div/section/section[2]/textarea</value>
      <webElementGuid>9a85dec6-f76c-4776-bc30-14f416ddf03e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>14acc4ac-efb0-4d51-8191-576dcd0c296a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
