<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add Work Location</name>
   <tag></tag>
   <elementGuidId>19053e08-c034-49ab-b406-01fe274fc20d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-primary.pull-right.action.create-action</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='New Flagging Request'])[2]/following::a[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b97d1522-9872-4097-bca9-bfe1d1b65cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>4708b750-bab8-4a3b-9094-ccee35a16053</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary pull-right action create-action</value>
      <webElementGuid>ee980672-7cd7-4a3f-9de6-690948e461f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Create</value>
      <webElementGuid>7f37f519-7184-479b-b63d-2d2565dfee7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4b184635-77d5-4bff-80d2-1c04117c3273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fab649fa-8f4a-454b-afa5-47e8a62147cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Work Location</value>
      <webElementGuid>c237ed72-ff6d-4d9f-90d8-29fe963bd343</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;worklocation&quot;)/div[@class=&quot;entity-grid subgrid&quot;]/div[@class=&quot;view-toolbar grid-actions clearfix&quot;]/div[@class=&quot;pull-right toolbar-actions&quot;]/div[@class=&quot;input-group pull-left&quot;]/a[@class=&quot;btn btn-primary pull-right action create-action&quot;]</value>
      <webElementGuid>eaedbd75-002b-415e-93ef-0e61565d84c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Flagging Request'])[2]/following::a[1]</value>
      <webElementGuid>11226087-5a11-4916-88de-97e630013b9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='. sort descending'])[1]/preceding::a[1]</value>
      <webElementGuid>5d349432-8fca-45d2-8a04-4a835036022d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='. sort descending'])[2]/preceding::a[2]</value>
      <webElementGuid>4a9db794-ae72-4b3c-814a-444b3f4fb944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Work Location']/parent::*</value>
      <webElementGuid>f4569270-65f3-4327-a300-c3f08636167d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='worklocation']/div/div/div/div/a</value>
      <webElementGuid>c83b8b75-92a3-4ca1-8d2a-65937f7805ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add Work Location')]</value>
      <webElementGuid>cffc8b89-fca0-4f2b-bc0e-beae538a8629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[3]</value>
      <webElementGuid>f9f41b71-e6c6-4e92-bbe9-381678ef00d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/a</value>
      <webElementGuid>1b8440d3-952c-4f6b-b865-31669b582e6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @class = 'btn btn-primary pull-right action create-action' and @title = 'Create' and (text() = 'Add Work Location' or . = 'Add Work Location')]</value>
      <webElementGuid>a0dc2c87-77a5-4885-94af-5192ecedefd3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
