<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_Create</name>
   <tag></tag>
   <elementGuidId>62aa930d-7a3a-4664-bc3c-2a90b5e93667</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1.modal-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/following::h1[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>b4d81af5-3446-4d5b-9e0d-e2db71af9c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-title</value>
      <webElementGuid>efe4341a-ca0f-4098-8cfb-34a3c8e8eaec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Create</value>
      <webElementGuid>e14225a6-6673-4bba-a53d-06143a6b19d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Create</value>
      <webElementGuid>158a5d7e-aec3-4da8-95fd-bfea6c3a00af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;worklocation&quot;)/div[@class=&quot;entity-grid subgrid&quot;]/section[@class=&quot;modal fade modal-form modal-form-insert in&quot;]/div[@class=&quot;modal-lg modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-header&quot;]/h1[@class=&quot;modal-title&quot;]</value>
      <webElementGuid>5996ad7e-8f1b-4cea-8b42-7e0299ddba08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Loading...'])[1]/following::h1[1]</value>
      <webElementGuid>1c3233e7-a7b5-49c9-8b36-b328c1215361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Error completing request.'])[1]/following::h1[1]</value>
      <webElementGuid>2a7fc6ff-b0aa-4123-93a7-7b241ca40caa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/preceding::h1[1]</value>
      <webElementGuid>f23c6772-a163-4767-a220-41932b6ba90e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/preceding::h1[1]</value>
      <webElementGuid>d208e7fe-26c2-46ef-bf9e-f2764806e03f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create']/parent::*</value>
      <webElementGuid>1bb7eefc-8073-46fd-8ae1-a179055f841c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='worklocation']/div/section/div/div/div/h1</value>
      <webElementGuid>90d59d3c-6554-4f94-bfc7-ace0b72ab9af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//section/div/div/div/h1</value>
      <webElementGuid>31a6749a-4281-4ae3-853b-53d098763be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@class = 'modal-title' and @title = 'Create' and (text() = ' Create' or . = ' Create')]</value>
      <webElementGuid>c99c6a6d-99f3-4755-bb6a-af614e1bd121</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
