<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_1</name>
   <tag></tag>
   <elementGuidId>5b8c1a26-f4c1-4398-bc7e-d66fe68e7911</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;Create dialog&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='worklocation']/div/section/div/div/div[2]/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>3cd9f068-0e81-4eba-8f9c-a7911b316c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-page</name>
      <type>Main</type>
      <value>/_portal/modal-form-template-path/6d6b3012-e709-4c45-a00d-df4b3befc518</value>
      <webElementGuid>79614073-820f-48e2-9216-f13343678a47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_portal/modal-form-template-path/6d6b3012-e709-4c45-a00d-df4b3befc518?entityformid=96b5410b-e123-e911-a96c-000d3a34afa9&amp;languagecode=1033&amp;refentity=cfra_flaggingrequest&amp;refid=55f1ddb6-2e50-ed11-97b0-00155da01d4a&amp;refrel=cfra_cfra_flaggingrequest_cfra_worklocation_FlaggingRequest</value>
      <webElementGuid>0e9ad4c2-f0b4-4f0c-a3a8-643cc7d126d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Create dialog</value>
      <webElementGuid>f9edb3bb-6f0c-41cb-abcc-edc79c9e919b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;worklocation&quot;)/div[@class=&quot;entity-grid subgrid&quot;]/section[@class=&quot;modal fade modal-form modal-form-insert in&quot;]/div[@class=&quot;modal-lg modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/iframe[1]</value>
      <webElementGuid>07cc5d46-2dc2-466d-88e7-e5503ac49775</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='worklocation']/div/section/div/div/div[2]/iframe</value>
      <webElementGuid>e95a8db0-c9b9-4482-ac7b-5e2943ef5169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>12e10bd2-1da5-4143-9593-ef46e9df4f1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Create dialog']</value>
      <webElementGuid>b84d9ee4-7a97-407e-85d9-1e58c5775927</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
