<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe</name>
   <tag></tag>
   <elementGuidId>dd96cc02-8c9b-4dc2-a034-918a7fbc9a76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe[title=&quot;Create&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@title = 'Create']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>a49c7938-2993-4c6d-be69-a67daf88ff45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-page</name>
      <type>Main</type>
      <value>/_portal/modal-form-template-path/6d6b3012-e709-4c45-a00d-df4b3befc518</value>
      <webElementGuid>5aa1890a-0a8d-446e-b605-13c91fe6448d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_portal/modal-form-template-path/6d6b3012-e709-4c45-a00d-df4b3befc518?entityformid=96b5410b-e123-e911-a96c-000d3a34afa9&amp;languagecode=1033&amp;refentity=cfra_flaggingrequest&amp;refid=8c2412b9-3050-ed11-97b0-00155da01d4a&amp;refrel=cfra_cfra_flaggingrequest_cfra_worklocation_FlaggingRequest</value>
      <webElementGuid>d321e864-6e7f-4095-902c-a9902c44e64e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Create</value>
      <webElementGuid>0775c4c7-7788-49e5-a1ea-e0db7d3aa6ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;worklocation&quot;)/div[@class=&quot;entity-grid subgrid&quot;]/section[@class=&quot;modal fade modal-form modal-form-insert in&quot;]/div[@class=&quot;modal-lg modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/iframe[1]</value>
      <webElementGuid>391a3157-97d7-485c-ae9d-d5c8b1feedc1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='worklocation']/div/section/div/div/div[2]/iframe</value>
      <webElementGuid>4fe604e7-3a48-42c5-a517-75fe08169123</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>5ab88208-ca49-4105-a173-15a5c2f4a353</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'Create']</value>
      <webElementGuid>2c84b36b-f3b0-4f7c-9286-9c52a2dfa1ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
