<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ctl00ctl00ContentContainerMainConten_73aaf2</name>
   <tag></tag>
   <elementGuidId>cd373c2f-fea5-4bdb-a982-cf84230d48b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cfra_tsssupportopt_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cfra_tsssupportopt_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff2fe06a-4b6a-45ed-ad93-f9d9a3fb1ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cfra_tsssupportopt_0</value>
      <webElementGuid>ed74c521-7381-4089-83cb-15389b87f892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>6bfd0acd-e8fd-4466-abc5-f51b79969afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$ContentContainer$MainContent$EntityControls$WebFormControl$EntityFormView$cfra_tsssupportopt</value>
      <webElementGuid>d4f955bf-ba1f-4bcd-9b86-31ebc304762d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>551380001</value>
      <webElementGuid>c13c5f04-5aba-400e-9ffe-5db9521683eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cfra_tsssupportopt_0&quot;)</value>
      <webElementGuid>f2f0a431-750f-49cf-b8ae-84a38f51f9b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cfra_tsssupportopt_0']</value>
      <webElementGuid>8dae7d3d-4fe5-4874-8520-44814fde329e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cfra_tsssupportopt']/input</value>
      <webElementGuid>dee317d1-9ff4-4c61-a384-0c96771fe72b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td/div[2]/span/input</value>
      <webElementGuid>563f5d01-ebb1-49c6-8232-d5c337ee7b41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'ctl00$ctl00$ContentContainer$MainContent$EntityControls$WebFormControl$EntityFormView$cfra_tsssupportopt']</value>
      <webElementGuid>be76d430-6a15-47da-a5d3-7c8aaa08291b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
