<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ctl00ctl00ContentContainerMainConten_654892</name>
   <tag></tag>
   <elementGuidId>c831d7b6-5223-4f58-9737-65c90e3efe74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cfra_asbestos_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cfra_asbestos_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2b368dab-f444-41f2-bfb4-2c61319cd6e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cfra_asbestos_0</value>
      <webElementGuid>2e7c6a52-db6d-4e0f-abf9-03206b5fe1a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>504e7df7-0595-4bab-95aa-aead1fa5da53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$ContentContainer$MainContent$EntityControls$WebFormControl$EntityFormView$cfra_asbestos</value>
      <webElementGuid>34f97132-3d75-446d-b00e-004ebe0117bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>551380000</value>
      <webElementGuid>780ab6bb-4d22-4aed-918e-5b65c7a0305d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cfra_asbestos_0&quot;)</value>
      <webElementGuid>50248acd-4e1b-450c-8c0e-ac42f435d729</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cfra_asbestos_0']</value>
      <webElementGuid>fc7b75a8-dd36-44e2-b858-e00dd02b0527</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cfra_asbestos']/input</value>
      <webElementGuid>238e218e-23c6-4240-983d-ec46dc253e1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/fieldset/table/tbody/tr/td/div[2]/span/input</value>
      <webElementGuid>0e0454ca-e8d3-4706-b56f-1f99001ff685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'ctl00$ctl00$ContentContainer$MainContent$EntityControls$WebFormControl$EntityFormView$cfra_asbestos']</value>
      <webElementGuid>86156377-8d18-4ac3-af0a-c2864603fd14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
