<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ctl00ctl00ContentContainerMainConten_afd06b</name>
   <tag></tag>
   <elementGuidId>08a276f9-5e5e-4947-b145-a171cbc24630</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cfra_dustgenerated_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cfra_dustgenerated_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f53727dc-06b9-46a0-b4f4-981f85a794be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cfra_dustgenerated_0</value>
      <webElementGuid>e5c3d378-3ce0-46b3-b786-67629209befe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1f2d66fe-b981-47f9-9f13-b7d54a3fc379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$ContentContainer$MainContent$EntityControls$WebFormControl$EntityFormView$cfra_dustgenerated</value>
      <webElementGuid>01037254-4feb-48ae-af8d-d0f6718f6067</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>551380000</value>
      <webElementGuid>15fd55b5-48ea-4f19-8b10-46c4a7bf34a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cfra_dustgenerated_0&quot;)</value>
      <webElementGuid>c49de9cd-ed3b-418f-b2ec-7ebfc4267c82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cfra_dustgenerated_0']</value>
      <webElementGuid>f2e7af41-b146-49e7-9fe1-54b1b8d7400c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cfra_dustgenerated']/input</value>
      <webElementGuid>f6d97914-8c10-459b-9ac9-eaf24cab9748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/fieldset/table/tbody/tr[2]/td/div[2]/span/input</value>
      <webElementGuid>36300671-ca5a-49c1-9db9-effab25bc253</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'ctl00$ctl00$ContentContainer$MainContent$EntityControls$WebFormControl$EntityFormView$cfra_dustgenerated']</value>
      <webElementGuid>95c3b85b-331b-49e2-bf87-1426704cbfc3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
