<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ctl00ctl00ContentContainerMainConten_b26de8</name>
   <tag></tag>
   <elementGuidId>af048eb2-fcab-49e9-a65b-973a74c77851</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cfra_ladders_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cfra_ladders_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8b1c545e-731f-468c-a73e-f7ad239331c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cfra_ladders_0</value>
      <webElementGuid>9c7fc8a1-d1a4-4951-8a4c-25ca0a8cf48b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>391e0e80-c82a-41cd-b566-f5400b502dcc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$ContentContainer$MainContent$EntityControls$WebFormControl$EntityFormView$cfra_ladders</value>
      <webElementGuid>222eb6db-1bc6-4ccc-98fc-cc24bb83255f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>551380000</value>
      <webElementGuid>5de56e49-9e7c-4c1a-89eb-478d143911fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cfra_ladders_0&quot;)</value>
      <webElementGuid>2e7b6eca-92f3-4a6e-a52a-4f314876936a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cfra_ladders_0']</value>
      <webElementGuid>534bb40f-c7df-4de5-b823-d221fb2e8692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cfra_ladders']/input</value>
      <webElementGuid>0b733722-11d5-4b18-b583-bf20cfadc4eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/div[2]/span/input</value>
      <webElementGuid>8ccbe2c5-d989-49bf-89c1-36529c22aa99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'ctl00$ctl00$ContentContainer$MainContent$EntityControls$WebFormControl$EntityFormView$cfra_ladders']</value>
      <webElementGuid>91e36e31-b2f9-4489-af20-7b14a91d33d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
