<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ctl00ctl00ContentContainerMainConten_20aea9</name>
   <tag></tag>
   <elementGuidId>db7ec69a-27d6-433b-b029-392a32801369</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cfra_poweroff_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cfra_poweroff_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e57330f1-3aec-4d2f-b89d-e5d6e197a72c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cfra_poweroff_0</value>
      <webElementGuid>83d11bdb-fd2e-49c4-a7b2-d5b036a8e500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>b50ea8f5-92ca-448f-8dda-d8d3fc567c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$ContentContainer$MainContent$EntityControls$WebFormControl$EntityFormView$cfra_poweroff</value>
      <webElementGuid>ff61f4c2-0a98-4bfd-a12a-ca17cdb08210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>551380000</value>
      <webElementGuid>ea730bcb-5a60-4b26-a2e8-77379218c72d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cfra_poweroff_0&quot;)</value>
      <webElementGuid>3b1d9d49-188d-48dc-982e-0081ace202e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cfra_poweroff_0']</value>
      <webElementGuid>8f17a9b9-25e2-4cbd-8799-7ae05dba7a24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cfra_poweroff']/input</value>
      <webElementGuid>db7df305-4bc7-4e9b-b82b-1b315bb09c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/div[2]/span/input</value>
      <webElementGuid>055c1885-f514-4929-84c1-c4ce335bf0cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'ctl00$ctl00$ContentContainer$MainContent$EntityControls$WebFormControl$EntityFormView$cfra_poweroff']</value>
      <webElementGuid>6c3fccc3-283c-4256-b365-d0620f9dcbbc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
