<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ctl00ctl00ContentContainerMainConten_40fdfe</name>
   <tag></tag>
   <elementGuidId>28dec95f-d07e-434b-a7f7-14d073a3bd41</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cfra_generalorder_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cfra_generalorder_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fcddcaa4-609a-41ec-8345-b236291136e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cfra_generalorder_0</value>
      <webElementGuid>007bc23f-6faf-453d-b0fb-50f9be4ff3d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ce6eebac-8a46-4e34-a705-38cf17bb9da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$ContentContainer$MainContent$EntityControls$WebFormControl$EntityFormView$cfra_generalorder</value>
      <webElementGuid>e7e807dd-d92c-44df-a59d-f7f9d3ad5a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>551380000</value>
      <webElementGuid>39ff58ef-5cb1-4b9e-a18e-338a26502c71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cfra_generalorder_0&quot;)</value>
      <webElementGuid>b094ea48-0fc4-46e7-b22f-77f0b4e78860</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cfra_generalorder_0']</value>
      <webElementGuid>ff2d893e-5088-43c6-9098-ef57272ec52a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cfra_generalorder']/input</value>
      <webElementGuid>2e917390-1d78-4c09-b777-1d14020d9951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>1dd2105f-edb2-4b43-b9b1-4263616d9c06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'ctl00$ctl00$ContentContainer$MainContent$EntityControls$WebFormControl$EntityFormView$cfra_generalorder']</value>
      <webElementGuid>3d267fdd-038e-41e5-8e5b-a8d552ad20e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
