<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ctl00ctl00ContentContainerMainConten_86c811</name>
   <tag></tag>
   <elementGuidId>bf742bce-d99b-40ff-8f23-6c57d712c249</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cfra_piggyback_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cfra_piggyback_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b6e428b-33e7-4651-a32b-b981f0f8419d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cfra_piggyback_0</value>
      <webElementGuid>2199a717-b797-45e7-9596-500b50135e71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>9d177c5f-97af-4f71-b874-45594bf8f223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ctl00$ContentContainer$MainContent$EntityControls$WebFormControl$EntityFormView$cfra_piggyback</value>
      <webElementGuid>d087e2f1-11cc-4984-919b-8fde40671404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>551380000</value>
      <webElementGuid>f6a7aa8b-e304-4b50-8c29-fa6a68d23428</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cfra_piggyback_0&quot;)</value>
      <webElementGuid>91411884-7aca-45d1-9d16-0248aa09e000</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cfra_piggyback_0']</value>
      <webElementGuid>d9821bf6-64ab-4686-ad2a-e8464bedf0dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cfra_piggyback']/input</value>
      <webElementGuid>4172887f-16c5-4a60-b9bd-6dc75e87de2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div[2]/span/input</value>
      <webElementGuid>c1dba1d5-e7f3-45b1-929d-f3c10d992013</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'ctl00$ctl00$ContentContainer$MainContent$EntityControls$WebFormControl$EntityFormView$cfra_piggyback']</value>
      <webElementGuid>47eb7476-caf7-43da-b795-945080cfcca7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
