<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__ctl00ContentContainerMainContentEnti_aa73d4</name>
   <tag></tag>
   <elementGuidId>f024eb1a-dd1e-4e8e-b09a-66d1e8151750</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cfra_division_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cfra_division_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b4dfa6e8-9dd3-4259-83a9-78ff76d2e438</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cfra_division_0</value>
      <webElementGuid>02d3f8bd-2a2e-46e9-b9fb-2553fd587283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>052c73f7-b60b-4550-ad8d-b85d6274ad23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentContainer$MainContent$EntityFormControl$EntityFormControl_EntityFormView$cfra_division</value>
      <webElementGuid>967bcf3d-ef03-485f-87aa-3699f24e3f8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>551380000</value>
      <webElementGuid>0a333769-70f7-42e7-8e2d-18c9c5604e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cfra_division_0&quot;)</value>
      <webElementGuid>93521a8c-fbbb-4c41-8a88-ffae3a354ec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OR PowerAppsportal/Page_New Flagging Request Partner Portal/iframe_1</value>
      <webElementGuid>26eee6cd-0b91-4b85-bad9-c5b6d5a7a1b9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cfra_division_0']</value>
      <webElementGuid>95c217b5-a828-490c-bc9b-5dd266b85e5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='cfra_division']/input</value>
      <webElementGuid>eea0a545-1624-4922-87e3-9c3875af6863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>977f77f4-1cef-4f9e-b59a-16ce55cae696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'ctl00$ContentContainer$MainContent$EntityFormControl$EntityFormControl_EntityFormView$cfra_division']</value>
      <webElementGuid>882aac85-ef68-4447-b953-e901a33be8f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
