<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_sort descending_fa fa-fw fa-check</name>
   <tag></tag>
   <elementGuidId>1cb21d20-fdc2-4b2f-8919-71df7a6f26a7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-fw.fa-check</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cfra_stationto_lookupmodal']/div/section/div/div/div[2]/div[2]/div[2]/table/tbody/tr/td/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b236f257-2812-47af-a7a6-bde2ce22e5a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-fw fa-check</value>
      <webElementGuid>aeb6e7b8-c579-4ba4-bfe4-7a35e0d67b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>97f642df-e882-4dd0-8316-e986c8a7fdd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>93355eb9-4cfe-427d-b1aa-27fa415d81cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select or deselect the row</value>
      <webElementGuid>e2b122c7-85c1-480b-a71c-8ab463c9af05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Checkbox</value>
      <webElementGuid>e87fe417-2b78-4e08-81e5-7ddc75e00cd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a6291026-d98b-4aa4-912a-effbb5bb69a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cfra_stationto_lookupmodal&quot;)/div[@class=&quot;entity-lookup&quot;]/section[@class=&quot;modal fade modal-lookup in&quot;]/div[@class=&quot;modal-lg modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;entity-grid&quot;]/div[@class=&quot;view-grid has-pagination&quot;]/table[@class=&quot;table table-fluid table-hover&quot;]/tbody[1]/tr[@class=&quot;selected info&quot;]/td[1]/span[@class=&quot;fa fa-fw fa-check&quot;]</value>
      <webElementGuid>159c84a1-c0ed-4159-af59-ac48774b161f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OR PowerAppsportal/Page_New Flagging Request Partner Portal/iframe_1</value>
      <webElementGuid>7dcff007-c7bd-41b9-bcbb-695372aeaec1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cfra_stationto_lookupmodal']/div/section/div/div/div[2]/div[2]/div[2]/table/tbody/tr/td/span</value>
      <webElementGuid>ad166b96-82fd-4430-b5ef-9ae53fb83439</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div[2]/div[2]/div/section/div/div/div[2]/div[2]/div[2]/table/tbody/tr/td/span</value>
      <webElementGuid>60c8ff45-cdc4-40c5-847f-b4391278dc6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@class = 'fa fa-fw fa-check' and @aria-label = 'Select or deselect the row' and @title = 'Checkbox']</value>
      <webElementGuid>43ef9341-41ba-4bdd-8630-aa52cfa68b58</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
