<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_sort descending_fa fa-fw</name>
   <tag></tag>
   <elementGuidId>8571ade4-76f7-4070-a70d-c80c13fa9ec5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-fw</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cfra_jobnumber_lookupmodal']/div/section/div/div/div[2]/div[2]/div[2]/table/tbody/tr/td/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e6c06366-d8d1-47d9-a2e5-f94b03367b89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-fw</value>
      <webElementGuid>5736716e-6fbe-47d1-a560-def85a7f4e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>369df6b3-e2b9-4340-9955-92c7a14e12d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select or deselect the row</value>
      <webElementGuid>12b91e30-2d05-4fa7-88fb-7949e162bc3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Checkbox</value>
      <webElementGuid>185d8b2a-bd10-4c43-96a0-658865bf40c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7fb7e0fb-10e7-468a-86a1-59f457b1da1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>99602fd2-30f1-4d02-a9fc-7403392ec32c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cfra_jobnumber_lookupmodal&quot;)/div[@class=&quot;entity-lookup&quot;]/section[@class=&quot;modal fade modal-lookup in&quot;]/div[@class=&quot;modal-lg modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;entity-grid&quot;]/div[@class=&quot;view-grid has-pagination&quot;]/table[@class=&quot;table table-fluid table-hover&quot;]/tbody[1]/tr[1]/td[1]/span[@class=&quot;fa fa-fw&quot;]</value>
      <webElementGuid>ea545df1-2a0b-45a3-b500-195d5cd04cab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cfra_jobnumber_lookupmodal']/div/section/div/div/div[2]/div[2]/div[2]/table/tbody/tr/td/span</value>
      <webElementGuid>cc5042ce-0bb6-462e-bfab-48de79c94696</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span</value>
      <webElementGuid>2a467a20-3335-4b27-9ca5-18eb8d968538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@class = 'fa fa-fw' and @aria-label = 'Select or deselect the row' and @title = 'Checkbox']</value>
      <webElementGuid>5e04330c-9e96-464e-85e3-b81704ea7817</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
