<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Launch lookup modal_fa fa-search</name>
   <tag></tag>
   <elementGuidId>e408f770-d5fd-4e9f-a684-437d8109c09f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='EntityFormView']/div[2]/div/div/fieldset/table/tbody/tr[2]/td/div[2]/div/div[2]/button[2]/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>76c58ec2-6e3c-43f2-8daf-49aa9522905c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-search</value>
      <webElementGuid>15531a6e-1bff-4ba7-93d8-124bffb3cd3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8642baec-b7e4-485f-b206-e9a282ffa0ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;EntityFormView&quot;)/div[@class=&quot;tab clearfix&quot;]/div[@class=&quot;tab-column&quot;]/div[1]/fieldset[1]/table[@class=&quot;section&quot;]/tbody[1]/tr[2]/td[@class=&quot;clearfix cell lookup form-control-cell&quot;]/div[@class=&quot;control&quot;]/div[@class=&quot;input-group&quot;]/div[@class=&quot;input-group-btn&quot;]/button[@class=&quot;btn btn-default launchentitylookup&quot;]/span[@class=&quot;fa fa-search&quot;]</value>
      <webElementGuid>ee77f102-f876-4b27-b2cf-8e0a2cebe2cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='EntityFormView']/div[2]/div/div/fieldset/table/tbody/tr[2]/td/div[2]/div/div[2]/button[2]/span[2]</value>
      <webElementGuid>59959571-db77-4eda-ac4e-d7d297e0b4f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span[2]</value>
      <webElementGuid>224cd26f-9d37-4584-bfbc-316fcbe33c9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@class = 'fa fa-search']</value>
      <webElementGuid>74686947-9039-4fc0-aa89-1a00646de226</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
