<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_sort descending_fa fa-fw (2)</name>
   <tag></tag>
   <elementGuidId>022a6ab3-6f26-45c6-b45a-155720058b5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-fw</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cfra_stationto_lookupmodal']/div/section/div/div/div[2]/div[2]/div[2]/table/tbody/tr/td/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>144bba8f-5149-4735-8e2c-b8dc86c67d1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-fw</value>
      <webElementGuid>d2003418-3d6a-4a8b-a096-a3f7159638a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>de109ee8-3f71-48eb-9736-bfd15356ec8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select or deselect the row</value>
      <webElementGuid>aaf80bc7-8658-4d54-9a05-c0a8416ef28c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Checkbox</value>
      <webElementGuid>6dec5dfc-3d17-416d-8122-efe14b432b27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1c0b5b99-1f8d-4cad-9d02-70f97bb27d2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>659ddd9e-cd56-47f7-b6bf-d0b28632e1ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cfra_stationto_lookupmodal&quot;)/div[@class=&quot;entity-lookup&quot;]/section[@class=&quot;modal fade modal-lookup in&quot;]/div[@class=&quot;modal-lg modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;entity-grid&quot;]/div[@class=&quot;view-grid has-pagination&quot;]/table[@class=&quot;table table-fluid table-hover&quot;]/tbody[1]/tr[1]/td[1]/span[@class=&quot;fa fa-fw&quot;]</value>
      <webElementGuid>e16e65f9-99ae-494b-b0cb-afa78c1c88d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OR PowerAppsportal/Page_New Flagging Request Partner Portal/iframe_1</value>
      <webElementGuid>cf74f645-78f3-482a-a349-e6b8bd01147b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cfra_stationto_lookupmodal']/div/section/div/div/div[2]/div[2]/div[2]/table/tbody/tr/td/span</value>
      <webElementGuid>7609682b-dc81-42d4-8a8c-f84ee2824689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span</value>
      <webElementGuid>f17e9b8b-4152-434a-b7df-53240a9697ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@class = 'fa fa-fw' and @aria-label = 'Select or deselect the row' and @title = 'Checkbox']</value>
      <webElementGuid>cf1a8e2b-a4b5-4dcd-8345-8f42b5e96725</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
