<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_sort descending_fa fa-fw (1)</name>
   <tag></tag>
   <elementGuidId>245e06bc-59da-408b-96e6-b20abc1142ef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.fa.fa-fw</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>15a801e8-4f96-4fed-8378-4b0890e97052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-fw</value>
      <webElementGuid>ec146672-7b87-404c-adf4-c482f820345e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>9234aa54-e2b8-47be-a14b-88d77eb96b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Select or deselect the row</value>
      <webElementGuid>d64074ed-de20-4e73-92ff-04c28077d841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Checkbox</value>
      <webElementGuid>23e47d51-eb18-4451-af71-efea6fdaa52b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>023689e4-c3c2-4cf3-a0fc-16a33a6f745d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3a4a0a07-0e3c-4d90-9209-558434eb65b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cfra_stationfrom_lookupmodal&quot;)/div[@class=&quot;entity-lookup&quot;]/section[@class=&quot;modal fade modal-lookup in&quot;]/div[@class=&quot;modal-lg modal-dialog&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;entity-grid&quot;]/div[@class=&quot;view-grid has-pagination&quot;]/table[@class=&quot;table table-fluid table-hover&quot;]/tbody[1]/tr[1]/td[1]/span[@class=&quot;fa fa-fw&quot;]</value>
      <webElementGuid>4355da34-e9a1-4b99-8348-2211a8ebb984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OR PowerAppsportal/Page_New Flagging Request Partner Portal/iframe</value>
      <webElementGuid>1d7db736-9918-4122-ab4a-a438772e5909</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cfra_stationfrom_lookupmodal']/div/section/div/div/div[2]/div[2]/div[2]/table/tbody/tr/td/span</value>
      <webElementGuid>2308b6f8-0886-4466-9e5a-d8770c9e3062</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/span</value>
      <webElementGuid>9cdcedb4-d790-4b28-950a-d459e8beec47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@class = 'fa fa-fw' and @aria-label = 'Select or deselect the row' and @title = 'Checkbox']</value>
      <webElementGuid>641e8aef-e280-456b-be6a-9b52638a4f3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
