<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea__ctl00ContentContainerMainContentE_4ebc8e</name>
   <tag></tag>
   <elementGuidId>5ecfdcd1-60c9-483b-8977-0549e4836dc5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cfra_notes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='cfra_notes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>57e49c9e-f6f1-443e-a86f-134b93b3dd00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ctl00$ContentContainer$MainContent$EntityFormControl$EntityFormControl_EntityFormView$cfra_notes</value>
      <webElementGuid>73d86461-7b76-492e-b322-566b420187fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>5e2b461e-12d0-4ef8-b909-c8d234997d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>7b9ff49d-95c0-49a3-bd72-85c2b7b5d6bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2000</value>
      <webElementGuid>031cb8b5-1d30-43af-b6a2-b5cc808805fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cfra_notes</value>
      <webElementGuid>62433b76-6c8f-4551-81ff-9fc2e6455757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>textarea form-control </value>
      <webElementGuid>2788f5a5-0609-4303-9a62-ecf87dc5a7c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>setIsDirty(this.id);</value>
      <webElementGuid>cd76a34c-7631-452d-85fa-7ddf8183efad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ab1a5de1-b92b-4014-b3f4-bcccfe4af5ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Work Location Specifics</value>
      <webElementGuid>305aa188-db4e-4be9-a1d9-65506e6617ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Work Location Specifics is a required field.</value>
      <webElementGuid>130a7b5c-0a1f-48e2-935c-96d613bb04cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>javascript:return LimitInput(this, event);</value>
      <webElementGuid>9079dc54-f137-4eb7-8d4a-103a78de8630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>javascript:return LimitInput(this, event);</value>
      <webElementGuid>e0e6d4b6-477c-4d08-ad2c-e4a4e30fdbae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onpaste</name>
      <type>Main</type>
      <value>javascript:return LimitPaste(this, event);</value>
      <webElementGuid>0c876d84-c5a1-4ca5-8c5f-90ffac245cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cfra_notes&quot;)</value>
      <webElementGuid>80604733-c57e-4a4c-b1ad-c6a6a15ee882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/OR PowerAppsportal/Page_New Flagging Request Partner Portal/iframe_1</value>
      <webElementGuid>dfcfc373-d723-46c6-b2f2-3edf7362aba1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='cfra_notes']</value>
      <webElementGuid>ddb6b63d-3462-4795-88a0-59e0ab13d6de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='EntityFormControl_EntityFormView']/div[2]/div/div/fieldset/table/tbody/tr[5]/td/div[2]/textarea</value>
      <webElementGuid>edb02494-b1f1-44ba-adf0-1bf68ec3dc74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>51606075-8f90-4e9d-b97e-7f28e1492bc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'ctl00$ContentContainer$MainContent$EntityFormControl$EntityFormControl_EntityFormView$cfra_notes' and @class = 'textarea form-control ' and @aria-label = 'Work Location Specifics' and @title = 'Work Location Specifics is a required field.']</value>
      <webElementGuid>4ef8e4c9-40da-4ccc-924f-9810791826a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
